# ndarry的索引(index),切割(slice)

In [6]:
import numpy as np

arr = np.arange(10)
arr[0]
arr[-1]
arr[:3]
arr[-3:]

array([7, 8, 9])

In [7]:
import random
random.randint(50,100)

95

In [13]:
np.random.randint(50, 101, size=5)
scores = np.random.randint(50,101, size=(50, 5))
scores.size
scores.shape

(50, 5)

In [16]:
scores[:,0]
scores[:,0:1]

array([[ 97],
       [ 54],
       [ 91],
       [ 60],
       [ 64],
       [ 85],
       [ 55],
       [ 76],
       [ 54],
       [ 82],
       [ 56],
       [ 60],
       [100],
       [ 53],
       [ 61],
       [ 93],
       [ 71],
       [ 66],
       [ 66],
       [ 72],
       [ 91],
       [ 95],
       [ 77],
       [ 74],
       [ 61],
       [ 56],
       [ 94],
       [ 74],
       [ 93],
       [ 96],
       [ 51],
       [ 85],
       [ 69],
       [ 71],
       [ 51],
       [ 89],
       [ 51],
       [ 83],
       [ 97],
       [ 85],
       [ 98],
       [ 82],
       [ 58],
       [ 92],
       [ 53],
       [ 66],
       [ 51],
       [ 95],
       [ 73],
       [ 89]])

In [19]:
scores[0,:]
scores[0:1,:]

array([[ 97,  54,  92, 100,  92]])

In [23]:
np.sum(scores,axis=1)
np.mean(scores, axis=1)

array([87. , 67.2, 75.4, 75.6, 71.6, 79. , 67.6, 82.4, 73.6, 79.2, 62.2,
       75.8, 77.4, 66.6, 79.6, 89. , 76.4, 73.8, 73.4, 63.4, 71.8, 87.4,
       76.8, 74.6, 72.4, 73. , 73.4, 81. , 83.8, 88.8, 70. , 70.4, 81.2,
       74.4, 65.2, 83.8, 84. , 68.8, 83.2, 85.6, 80.2, 79. , 66.2, 76.4,
       69.8, 75.2, 69.2, 79.8, 74.6, 71.4])