https://www.perplexity.ai/search/1f6d8098-e981-44bf-b915-b14b9e9052da

In [2]:
import numpy as np
np.array(1, 3, 5, 7, 9)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [3]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [2]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [5]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.random.rand(3, 4)

array([[0.34209382, 0.65828282, 0.88847999, 0.04186168],
       [0.30973815, 0.23465116, 0.50992705, 0.96714605],
       [0.645478  , 0.79852128, 0.05106867, 0.46669292]])

In [7]:
scores = np.random.randint(50,101,size=(50, 5))