https://www.perplexity.ai/search/27854047-0059-44b3-b1ed-b6dbdddd6505

### numpy的索引和切割

In [1]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[ 97,  83,  77,  90,  72],
       [ 61,  55,  63,  89,  78],
       [ 57,  54,  67,  62,  50],
       [ 66, 100,  56,  83,  75],
       [ 66,  68,  97,  67,  56]])

In [2]:
scores[:3,2:]

array([[77, 90, 72],
       [63, 89, 78],
       [67, 62, 50]])

In [3]:
scores[4]
scores[4,:]
scores[4:,:]

array([[66, 68, 97, 67, 56]])

In [4]:
scores[:,:2]

array([[ 97,  83],
       [ 61,  55],
       [ 57,  54],
       [ 66, 100],
       [ 66,  68]])

#### numpy的統計工具

In [5]:
scores = np.random.randint(50,101,size=(5,5))
scores

array([[ 99,  53,  60,  71,  83],
       [ 84,  95,  52,  82,  56],
       [ 73,  54,  62,  60,  66],
       [ 54,  81,  91, 100,  64],
       [ 77,  97,  98,  50,  96]])

In [6]:
scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]

array([366, 369, 315, 390, 418])

In [7]:
#加總
np.sum(scores,axis=1)

array([366, 369, 315, 390, 418])

In [8]:
#平均
np.mean(scores, axis=1)

array([73.2, 73.8, 63. , 78. , 83.6])

In [9]:
#最大
np.max(scores,axis=1)

array([ 99,  95,  73, 100,  98])

In [10]:
#最小
np.min(scores,axis=1)

array([53, 52, 54, 54, 50])

In [11]:
#中間數
np.median(scores,axis=1)

array([71., 82., 62., 81., 96.])

In [12]:
#標準差
np.std(scores,axis=1)

array([16.42437213, 16.80952111,  6.32455532, 16.9351705 , 18.51053754])